import chapter4.sec1.failingFn
import chapter4.sec1.failingFn2

// Section 1

// Throws an exception, see the Scratch Output window.
//failingFn(12)

failingFn2(12)

"112".toInt()

// "hello".toInt()
